import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ThemeToggleBtn } from '@/component/ThemeToggleBtn'
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 200 300 400 500 600 700 800 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 200 300 400 500 600 700 800 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className="bg-white dark:bg-black">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add('dark')
                    localStorage.setItem('theme', 'dark')
                  } else {
                    document.documentElement.classList.remove('dark')
                    localStorage.setItem('theme', 'light')
                  }
                } catch (_) {}
              })()
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1600px] min-w-[1024px] mx-auto`}>
        <header className="flex justify-between">
          <h2>권현우</h2>
          <ThemeToggleBtn />
        </header>
        <div className="bg-red dark:bg-blue">{children}</div>
      </body>
    </html>
  )
}
